[package]
name = "zydeco-lang"
version = "0.0.1"
edition = "2021"
description = "A language implementation for zydeco, a call-by-push-value language"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = { version = "0.19", features = ["lexer"] }
regex = "1"
clap = { version = "4", features = ["derive"] }

# Add a build-time dependency on the lalrpop library:
[build-dependencies]
lalrpop = "0.19"
