[package]
name = "zydeco-lang"
version = "0.0.1"
edition = "2021"
description = "A language implementation for zydeco, a call-by-push-value language"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
logos = "0.12"
lalrpop-util = { version = "0.19", features = ["lexer"] }
enum_dispatch = "0.3"
indexmap = "1.9"

# Add a build-time dependency on the lalrpop library:
[build-dependencies]
lalrpop = "0.19"
